name: alqadiya_game
description: "A new Flutter project."
publish_to: 'none' 
version: 1.0.0+5
environment:
  sdk: ^3.7.2


dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.8
  get: ^4.7.2
  cached_network_image: ^3.4.1
  shimmer: ^3.0.0
  dio: ^5.8.0+1
  http: ^1.2.0
  fluttertoast: ^8.2.12
  google_fonts: ^6.2.1
  flutter_svg: ^2.1.0
  pinput: ^5.0.1
  share_plus: ^11.0.0
  calendar_date_picker2: ^2.0.1
  flutter_screenutil: ^5.9.3
  iconsax: ^0.0.8
  image_picker: ^1.1.2
  firebase_core: ^3.14.0
  google_sign_in: ^6.3.0
  sign_in_with_apple: ^7.0.1
  flutter_spinkit: ^5.2.1
  google_maps_flutter: ^2.12.3
  auto_size_text: ^3.0.0
  another_flushbar: ^1.12.30
  url_launcher: ^6.3.2
  geolocator: any
  open_file: ^3.5.10
  pdf: ^3.11.3
  just_audio: ^0.9.40
  syncfusion_flutter_pdfviewer: ^28.1.6
  shared_preferences: ^2.5.3
  just_the_tooltip: ^0.0.12
  local_auth: ^2.3.0
  cached_video_player_plus: ^4.0.4
  video_player: ^2.10.1
  logger: ^2.6.2


dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0
#   flutter_launcher_icons: ^0.14.4

# flutter_launcher_icons:
#   android: "ic_launcher"
#   ios: true
#   remove_alpha_ios: true
#   image_path: "assets/images/app_icon.png"
#   min_sdk_android: 24 # android min sdk min:16, default 21


flutter:
  uses-material-design: true

  assets:
    - assets/images/
    - assets/icons/
    - assets/

flutter_native_splash:
  color: "#FFFFFF"
  image: assets/images/nativesplash.png
  android: true
  ios: true
  web: false
